const DISPOSABLE_DOMAINS = new Set([
  // Guerrilla Mail family
  'guerrillamail.com','guerrillamail.net','guerrillamail.org','guerrillamail.de',
  'guerrillamail.biz','guerrillamail.info','guerrillamailblock.com','grr.la',
  'sharklasers.com','spam4.me',
  // Mailinator family
  'mailinator.com','mailinator2.com','suremail.info','spamherelots.com',
  'spamhereplease.com','mailinater.com','getonemail.com',
  // 10MinuteMail family
  '10minutemail.com','10minutemail.net','10minutemail.org','10minutemail.de',
  '10minutemail.co.uk','10minutemail.ru','10minutemail.be','10minutemail.cf',
  '20minutemail.com','minutemail.com',
  // Temp-Mail / YopMail
  'temp-mail.org','tempmail.com','tempmail.net','tempmail.org','tempmail.us',
  'yopmail.com','yopmail.fr','cool.fr.nf','jetable.fr.nf','nospam.ze.tc',
  'nomail.xl.cx','mega.zik.dj','speed.1s.fr','courriel.fr.nf','moncourrier.fr.nf',
  'monemail.fr.nf','monmail.fr.nf',
  // Trash / Discard mail
  'trashmail.com','trashmail.at','trashmail.io','trashmail.me','trashmail.net',
  'trashmail.org','trashmail.xyz','trashinbox.com','trashdevil.com','trashdevil.de',
  'discardmail.com','discardmail.de','discard.email','dispostable.com',
  // Throwaway
  'throwaway.email','throwam.com','throwam.com',
  // Others
  'fakeinbox.com','fakeinbox.org','maildrop.cc','mailnesia.com','mailnull.com',
  'mailexpire.com','mailscrap.com','spamgourmet.com','spamgourmet.net',
  'spamgourmet.org','spambox.us','spambog.com','spamevader.net',
  'incognitomail.com','mytrashmail.com','emailondeck.com','tempinbox.com',
  'filzmail.com','crapmail.org','jetable.net','jetable.org',
  'nwldx.com','wegwerfmail.de','wegwerfmail.net','wegwerfmail.org',
  'sofimail.com','sofort-mail.de','speed.1s.fr',
  'spam.la','spaml.com','spaml.de','spamoff.de','spamspot.com',
  'binkmail.com','bobmail.info','dayrep.com','delikkt.de','disign-concept.eu',
  'disign-revelation.com','einrot.com','einrot.de','enterto.com','filzmail.com',
  'frapmail.com','get1mail.com','getonemail.net','girlsundertheinfluence.com',
  'gishpuppy.com','great-host.in','greensloth.com','h.mintemail.com',
  'hartbot.de','hat-geld.de','herp.in','hmamail.com','hochsitze.com',
  'hulapla.de','ieatspam.eu','ieatspam.info','ieh-mail.de','inoutmail.de',
  'inoutmail.eu','inoutmail.info','inoutmail.net','ipoo.org','irish2me.com',
  'iwi.net','jetable.com','jobbikszimpatizans.hu','jourrapide.com','jumonji.tk',
  'kasmail.com','klassmaster.com','klassmaster.net','koszmail.pl','kurzepost.de',
  'letthemeatspam.com','lhsdv.com','lifebyfood.com','link2mail.net','litedrop.com',
  'lol.ovpn.to','lolfreak.net','lookugly.com','lortemail.dk','lukecarrier.me',
  'maboard.com','mail.mezimages.net','mail2rss.org','mail4trash.com',
  'mailbidon.com','mailbucket.org','mailcat.biz','mailcatch.com','maileimer.de',
  'mailfa.tk','mailfreeonline.com','mailguard.me','mailin8r.com','mailme.lv',
  'mailme24.com','mailmetrash.com','mailmoat.com','mailnew.com','mailnull.com',
  'mailpick.biz','mailrock.biz','mailsac.com','mailshell.com','mailsiphon.com',
  'mailslapping.com','mailslite.com','mailsworth.com','mailtome.de',
  'mailtothis.com','mailzilla.com','mbx.cc','mega.zik.dj','meinspamschutz.de',
  'meltmail.com','messagebeamer.de','mezimages.net','mierdamail.com',
  'migumail.com','mintemail.com','moburl.com','moncourrier.fr.nf','monemail.fr.nf',
  'monmail.fr.nf','mt2009.com','mt2014.com','mx0.wwwnew.eu','mycleaninbox.net',
  'mypartyclip.de','myphantomemail.com','mysamp.de','myspaceinc.net',
  'myspamless.com','mytemp.email','mythirdage.com','mytrashmail.com',
  'nabuma.com','netzidiot.de','neuro.md','neutralinbox.com','no-spam.ws',
  'noblepioneer.com','nomail.pw','nomail.xl.cx','nomail2me.com','nospam.ze.tc',
  'nospamfor.us','nospamthanks.info','notmailinator.com','nowmymail.com',
  'nullbox.info','o2.co.uk','obobbo.com','odaymail.com','one-time.email',
  'oneoffemail.com','oneoffmail.com','onewaymail.com','online.ms','oopi.org',
  'ovpn.to','owlpic.com','pancakemail.com','paplease.com','payspade.com',
  'pcusers.otherinbox.com','phreaker.net','plexolan.de','pookmail.com',
  'proxymail.eu','prtnx.com','prtz.eu','pubmail.io','punkass.com',
  'put2.net','putthisinyourspamdatabase.com','qq.com',
  'quickinbox.com','rcpt.at','reallymymail.com','reconmail.com','recyclemail.dk',
  'regbypass.com','regbypass.comsafe-mail.net','rejectmail.com','rklips.com',
  'rmqkr.net','rn.com','rtrtr.com','s0ny.net','safe-mail.net','safersignup.de',
  'safetymail.info','safetypost.de','sandelf.de','schafmail.de','schrott-mail.de',
  'secretemail.de','secure-mail.biz','shiftmail.com','shitmail.me','shortmail.net',
  'sibmail.com','sinfiltro.cl','sinnlos-mail.de','siteposter.net','skeefmail.com',
  'slapsfromlastnight.com','slaskpost.se','slave-auctions.net','slippery.email',
  'slopsbox.com','slowslow.de','slushmail.com','smashmail.de','smellfear.com',
  'snakemail.com','sneakemail.com','sneakmail.de','snkmail.com','socialfurry.org',
  'sofimail.com','sofort-mail.de','sogetthis.com','spambob.com','spambob.net',
  'spambob.org','spamcon.org','spamcorptastic.com','spamcowboy.com','spamcowboy.net',
  'spamcowboy.org','spamday.com','spamex.com','spamfree24.de','spamfree24.eu',
  'spamfree24.info','spamfree24.net','spamfree24.org','spamgoes.in',
  'spamgourmet.com','spamgourmet.net','spamgourmet.org','spamherelots.com',
  'spamhereplease.com','spamhole.com','spamify.com','spamkill.info',
  'spaml.com','spaml.de','spammotel.com','spamnull.com','spamoff.de',
  'spamspot.com','spamthis.co.uk','spamthisplease.com','spamtrail.com',
  'speed.1s.fr','spoofmail.de','stuffmail.de','super-auswahl.de',
  'supergreatmail.com','supermailer.jp','suremail.info','svk.jp','sweetxxx.de',
  'tafmail.com','tagyourself.com','tankmail.com','techemail.com',
  'tempalias.com','tempe-mail.com','tempemail.biz','tempemail.com',
  'tempemail.net','tempinbox.co.uk','tempinbox.com','temporaryemail.net',
  'temporaryemail.us','temporaryforwarding.com','temporaryinbox.com',
  'temporarymailaddress.com','tempthe.net','thanksnospam.com','thankyou2010.com',
  'thisisnotmyrealemail.com','throam.com','throwam.com','throwaway.email',
  'throwaways.info','tilien.com','timekr.top','tmp-email.net','tmailinator.com',
  'toiea.com','toomail.biz','topranklist.de','tradermail.info','trash-amil.com',
  'trash-mail.at','trash-mail.com','trash-mail.de','trash-mail.ga','trash-mail.io',
  'trash-mail.tk','trash-me.com','trashcanmail.com','trashimail.com',
  'trashmail.at','trashmail.com','trashmail.de','trashmail.io','trashmail.me',
  'trashmail.net','trashmail.org','trashmail.xyz','trashmailer.com',
  'trashymail.com','trbvm.com','tsamail.co.za','turual.com','twinmail.de',
  'tyldd.com','uggsrock.com','umail.net','unlimit.com','unmail.ru',
  'uroid.com','us.af','valemail.net','venompen.com','veryrealemail.com',
  'viditag.com','viewcastmedia.com','viewcastmedia.net','viewcastmedia.org',
  'votiputox.org','vubby.com','walala.org','walkmail.net','walkmail.ru',
  'webemail.me','weg-werf-email.de','wegwerf-emails.de','wegwerfadresse.de',
  'wegwerfmail.de','wegwerfmail.net','wegwerfmail.org','wh4f.org','whyspam.me',
  'willhackforfood.biz','willselfdestruct.com','winemaven.info','wronghead.com',
  'wuzup.net','wuzupmail.net','www.e4ward.com','www.mailinator.com',
  'wwwnew.eu','xagloo.com','xemaps.com','xents.com','xmaily.com',
  'xoxy.net','xww.ro','ycn.ro','yep.it','yepmail.net','yertxenor.tk',
  'yomail.info','yopmail.com','yopmail.fr','yopmail.pp.ua',
  'youmailr.com','ypmail.webarnak.fr.eu.org','yuurok.com','z1p.biz',
  'za.com','zehnminuten.de','zehnminutenmail.de','zetmail.com','zippymail.info',
  'zoemail.com','zoemail.net','zoemail.org','zomg.info',
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase().trim();
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}
