import { BRAND } from '@/lib/brand-colors';
import { DEFAULT_AI_BEAM } from '@/lib/widget-ai-beam';
import type { WidgetConfig } from './types';

export const DEFAULT_WIDGET_CONFIG: WidgetConfig = {
  name: 'Mi Widget',
  agentId: '',
  color: BRAND.primary,
  title: 'BotIvA Assistant',
  subtitle: 'Siempre aquí para ayudarte',
  welcome: '¡Hola! ¿En qué puedo ayudarte?',
  fabHint: '¿Necesitas ayuda?',
  avatar: '',
  fabAvatarSize: 86,
  position: 'bottom-right',
  theme: 'light',
  borderRadius: '16px',
  autoOpen: false,
  fabDismissible: true,
  voiceEnabled: true,
  imageUploadEnabled: true,
  micEnabled: true,
  humanSupportPhone: '',
  humanSupportEnabled: true,
  handoffNotifyMode: 'both',
  handoffEnabled: true,
  handoffTimeout: 5,
  feedbackEnabled: false,
  feedbackTitle: '¿Cómo fue tu experiencia?',
  feedbackThanks: '¡Gracias por tu feedback!',
  conversationIdleTimeout: 15,
  policyEnabled: true,
  policyText: '',
  policyLinkLabel: 'Política de Privacidad',
  policyUrl: '',
  multiAgentEnabled: false,
  multiAgentMode: 'triage',
  agentIds: [],
  orchestratorAgentIds: [],
  pipelineConfig: null,
  ...DEFAULT_AI_BEAM,
};
